name: Simple Github Action

on:
  push:
    branches:
      - "master"

jobs:
  build:
    name: Build dotnet application
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup dotnet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.x'
    - run: dotnet build
