name: Simple Github Action

on:
  push:
    branches:
      - "master"

jobs:
  build:
    name: Build dotnet application
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v4
    - name: Setup dotnet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.x'
    - run: dotnet build

    - name: Restore application
      run: dotnet restore

    - name: Publish
      run: dotnet publish

    - name: Finishing
      run: echo Success

  deploy:
    needs: build
    name: Deploy code to server
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            su -l abdulloh
            cd ~/dotnetdeploy/EntityFrameworkCoreLesson
            ./deploy.sh
